name: Setup
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.10.2

    - uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Set up foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install node modules
      run: pnpm install
      shell: bash
