on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Lint

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: Run Formatters
        run: pnpm format:check

      - name: Run Linters
        run: pnpm lint
